const { TextInputStyle } = require('discord.js');
const { getDepartments, updateDepartmentForm } = require('../../../database/database');
const { simpleEmbed } = require('../../../utils/embeds');
const { COLORS } = require('../../../utils/constants');
const logger = require('../../../utils/logger');

module.exports = {
    name: 'ready',
    once: true,
    execute(client) {
        // Handle "Add Question" Modal
        client.modals.set('config_question_add_', async (interaction) => {
            try {
                const deptId = interaction.customId.replace('config_question_add_', '');
                const label = interaction.fields.getTextInputValue('question_label');
                const placeholder = interaction.fields.getTextInputValue('question_placeholder');
                const styleStr = interaction.fields.getTextInputValue('question_style').toLowerCase();
                
                const style = (styleStr.includes('largo') || styleStr.includes('paragraph')) ? 2 : 1;

                const departments = getDepartments(interaction.guild.id);
                const dept = departments.find(d => String(d.id) === deptId);

                if (!dept) return interaction.reply({ content: 'Departamento no encontrado.', ephemeral: true });

                let questions = [];
                try {
                    if (dept.form_json) {
                        const parsed = JSON.parse(dept.form_json);
                        questions = Array.isArray(parsed) ? parsed : [{ id: 'legacy', label: parsed.label, placeholder: parsed.placeholder, style: parsed.style, required: true }];
                    }
                } catch (e) {
                    logger.error('Error parsing form_json:', e);
                }

                // Add new question
                const newQuestion = {
                    id: `q_${Date.now()}`,
                    label,
                    placeholder,
                    style,
                    required: true // Default to required for now, could add option later
                };
                
                questions.push(newQuestion);
                updateDepartmentForm(dept.id, interaction.guild.id, JSON.stringify(questions));

                await interaction.reply({
                    embeds: [simpleEmbed('✅ Pregunta Añadida', `Se ha añadido la pregunta **"${label}"** al departamento **${dept.name}**.`, COLORS.SUCCESS)],
                    ephemeral: true
                });
            } catch (err) {
                logger.error('Error in config_question_add handler:', err);
                interaction.reply({ content: 'Ocurrió un error procesando el formulario.', ephemeral: true }).catch(() => {});
            }
        });

        // Handle "Edit Question" Modal
        client.modals.set('config_question_edit_', async (interaction) => {
            try {
                // customId format: config_question_edit_DEPTID_QID
                // But QID might contain underscores too if generated by Date.now().
                // So we need to be careful with splitting.
                // deptId is integer (usually), but let's assume `qId` is the rest.
                
                const rawId = interaction.customId.replace('config_question_edit_', '');
                // Find index of first underscore (deptId is usually int, but let's find it)
                const firstUnderscore = rawId.indexOf('_');
                if (firstUnderscore === -1) return interaction.reply({ content: 'ID inválido.', ephemeral: true });

                const deptId = rawId.substring(0, firstUnderscore);
                const qId = rawId.substring(firstUnderscore + 1);

                const label = interaction.fields.getTextInputValue('question_label');
                const placeholder = interaction.fields.getTextInputValue('question_placeholder');
                const styleStr = interaction.fields.getTextInputValue('question_style').toLowerCase();
                const style = (styleStr.includes('largo') || styleStr.includes('paragraph')) ? 2 : 1;

                const departments = getDepartments(interaction.guild.id);
                const dept = departments.find(d => String(d.id) === deptId);

                if (!dept) return interaction.reply({ content: 'Departamento no encontrado.', ephemeral: true });

                let questions = [];
                try {
                    if (dept.form_json) {
                        const parsed = JSON.parse(dept.form_json);
                        questions = Array.isArray(parsed) ? parsed : [{ id: 'legacy', label: parsed.label, placeholder: parsed.placeholder, style: parsed.style, required: true }];
                    }
                } catch (e) { return interaction.reply({ content: 'Error leyendo configuración.', ephemeral: true }); }

                const qIndex = questions.findIndex(q => q.id === qId);
                if (qIndex === -1) return interaction.reply({ content: 'Pregunta no encontrada.', ephemeral: true });

                // Update
                questions[qIndex] = { ...questions[qIndex], label, placeholder, style };
                
                updateDepartmentForm(dept.id, interaction.guild.id, JSON.stringify(questions));

                await interaction.reply({
                    embeds: [simpleEmbed('✅ Pregunta Editada', `Se ha editado la pregunta **"${label}"** en **${dept.name}**.`, COLORS.SUCCESS)],
                    ephemeral: true
                });

            } catch (err) {
                 logger.error('Error in config_question_edit handler:', err);
                 interaction.reply({ content: 'Ocurrió un error procesando el formulario.', ephemeral: true }).catch(() => {});
            }
        });
        
        console.log('[Config] ✔ Interacciones de configuración registradas.');
    }
};
